---
jira:
  projectKey: "HSEARCH"
  ignore:
      # See the `build-dependencies` group in the Dependabot's configuration file
    - user: dependabot[bot]
      titlePattern: "Bump the build-dependencies group with \\d+ updates?"