---
jira:
  projectKey: "HSEARCH"
  ignore:
      # See the `build-dependencies` group in the Dependabot's configuration file
    - user: dependabot[bot]
      titlePattern: "Bump the build-dependencies group with \\d+ updates?"
  ignoreFiles:
    # Git
    - ".git*"
    - ".mailmap"
    # Maven
    - "mvnw*"
    - ".mvn/"
    # CI
    - ".github/"
    - "ci/"
    - "Jenkinsfile"
    - "*/Jenkinsfile"
    - "*.Jenkinsfile"
    - "*.sh"
    # In-repo documentation
    - "copyright.txt"
    - "README.md"
    - "MAINTAINERS.md"
    - "CONTRIBUTING.md"
    # Misc. build files
    - "build/config/"
    - "build/configuration-properties-collector/"
    - "build/container/"
    - "build/enforcer/"
    - "build/jqassistant/"
    - "build/reports/"
    - "build/script/"
develocity:
  buildScan:
    addCheck: true
    tags:
      - column: "OS"
        pattern: "Linux"
      - column: "OS"
        pattern: "Windows.*"
        replacement: "Windows"
      - column: "Java"
        pattern: "jdk-(.*)"
        replacement: "$1"
      - column: "Java"
        pattern: "compiler-(.*)"
        replacement: "$1"
      - column: "Backend"
        pattern: "elasticsearch-(.*)"
        replacement: "es-$1"
      - column: "Backend"
        pattern: "(.*-)?opensearch-(.*)"
        replacement: "$1os-$2"
      - column: "Backend"
        pattern: "lucene"
      - column: "DB"
        pattern: "h2|postgres(ql)?|mysql|mssql|derby|tidb|cockroach(db)?|oracle.*|db2"
        replacement: "$0"
      - pattern: "hibernate.search|elasticsearch|opensearch|main|HEAD|\\d+.\\d+|PR-\\d+"
        replacement: "" # Just remove these tags
