spring.datasource:
  driver-class-name: ${JDBC_DRIVER} # From environment variable
  url: ${JDBC_URL} # From environment variable
  username: ${JDBC_USERNAME} # From environment variable
  password: ${JDBC_PASSWORD} # From environment variable

logging.level:
  org.springframework.core.env: DEBUG