spring.jpa:
  properties:
    hibernate.search:
      backend:
        type: lucene
        analysis.configurer: luceneAnalysisConfigurer
        directory.root: ${LUCENE_ROOT_PATH} # From environment variable
