spring.jpa:
  properties:
    hibernate.search:
      default_backend: lucene1
      backends:
        lucene1:
          type: lucene
          analysis_configurer: luceneAnalysisConfigurer
          directory.root: ${LUCENE_ROOT_PATH} # From environment variable
