[[preface]]

[preface]
== Preface

This is a Google Summer of Code 2016 subject.

Mentors: Gunnar Morling and Emmanuel Bernard | Student: Mincong Huang

link:$$http://hibernate.org/search/$$[Hibernate Search] is an extension to
Hibernate ORM that brings the powers of full-text search via Apache Lucene and
Elasticsearch to JPA models. Think of it as Google: after processing the input
keywords (e.g. ignoring stop words and applying different kinds of
normalization), Hibernate Search returns results ordered by relevance. It brings
significant benefits comparing to normal SQL for search-related uses cases. Its
full-text index can be updated in two ways: automatically, whenever data changes
(using listeners hooked into Hibernate) or by means of the "mass indexer", which
rebuilds the entire index for given entity types.

This proposal aims to provide an alternative to the current mass indexer
implementation, using the Java Batch architecture as defined by
link:$$https://jcp.org/en/jsr/detail?id=352$$[JSR 352]. This standardized tool
JSR 352 provides task-and-chunk oriented processing, parallel execution and many
other optimization features. This batch job should accept the entity type(s) to
re-index as an input, load the relevant entities from the database and rebuild
the full-text index from these.

