[[user-guide]]
== User Guide


Hibernate Seach’s new MassIndexer uses the Batch approach introduced by JSR352.
It covers not only the existing functionalities of the previous indexer, but
also benefits the powerful standard based facilities of the java batch platform
(JSR352), such as checkpoint and step partitioning. It requires a batch runtime
for the execution. For Java EE users, the default batch runtime included in the
container will be used. For Java SE users, we’ve chosen JBeret SE for you.

.How to use the new MassIndexer?
====
[source, JAVA]
----
Long executionID = BatchIndexingJob.forEntity( MyEntity.class )
        .start();
----
====

This approach is optimized for best performance but requires to set the
application in maintenance mode. Running a mass indexer in busy hours is not
recommended. You also need to ensure the batch runtime has enough available
threads for the execution, because all the batch use the same thread pool.


=== Selection of entities
The mass indexer accepts selection of entity types through different methods,
which allows you to add one or multiple class types.

.How to add entity type(s) to selection?
====
[source, JAVA]
----
BatchIndexingJob.Builder builder1 = BatchIndexingJob.forEntity( Company.class );
BatchIndexingJob.Builder builder2 = BatchIndexingJob.forEntities( Company.class, Employee.class );
----
====

[NOTE]
====
Please notice that for instant, only the root entity types are accepted. It
should have no relationship between 2 root entities. Because relationships are
not implemented in the framework yet, such as one-to-many, many-to-many.
====

=== Parallelism
In order to maximize the performance, we highly recommend you to speed up the
mass indexer using parallelism. Parallelism is activated by default. Under the
standard JSR 352, the exact word is “partitioning”. The indexing step may run as
multiple partitions, one per thread. Each partition has its own partition ID and
parameters. If there’re more partitions than threads, partitions are considered
as a queue to consume: each thread can only run one partition at a time and
won’t consume the next partition until the previous one is finished.


==== Threads
The maximum number of threads used by the job execution is defined through
method `maxThreads()`. Within the N threads given, there’s 1 thread reserved for
the core, so only N - 1 threads are available for different partitions. The
default number is 10, which correspond to the default max number of threads in
JBeret, the WildFly batch runtime. However, you can overwrite it with your own
value.

====
[source, JAVA]
----
builder = builder.maxThreads( 5 );
----
====

[NOTE]
====
Note that the batch runtime cannot guarantee the requested number of threads are
available, it will use as it can up to the requested maximum. (JSR352 v1.0 Final
Release, page 34)
====


==== Partitions
Mass indexer defines dynamically the number of partitions, but you need to tell
it the number of rows per partitions so that it can calculate the partitions by
division.

====
[source, JAVA]
----
builder = builder.rowsPerPartition( 5000 );
----
====

Each partition deals with one root entity type, so 2 different entity types will
never run under the same partition.


==== Checkpoint
Mass indexer supports checkpoint algorithm. Assume that N is the value of
checkpoint frequency, then a partition will reach at checkpoint every N items
processed inside the partition. You can overwrite it to adapt your business
requirement. By default, it is set to 3.

====
[source, JAVA]
----
builder = builder.checkpointFreq( 1000 );
----
====

Checkpoint a partition-scope algorithm, which means each partition has its own
checkpoint counter and it is not shared with other partitions.


=== Selecting the persistence unit (EntityManagerFactory)

[CAUTION]
====
Regarless of how the entity manager factory is retrieved,
you must make sure that the entity manager factory used by the mass indexer
will stay open during the whole mass indexing process.
====

==== Plain java environment (no CDI)

If you use only one persistence unit, the mass indexer will be able to access
your database automatically without any special configuration:
you only have to make sure to create the `EntityManagerFactory` (or `SessionFactory`)
in your application before launching the mass indexer.

If you want to use multiple persistence unit,
you will have to add two parameters when launching the mass indexer:

 * `entityManagerFactoryReference`: this is the string that will identify the `EntityManagerFactory`.
 * `entityManagerFactoryScope`: this allows to select how you want to reference the `EntityManagerFactory`.
   Possible values are:
   
 ** `persistence-unit-name` (the default): use the persistence unit name defined
      in `persistence.xml`.
 ** `session-factory-name`: use the session factory name
      defined in the Hibernate configuration by the `hibernate.session_factory_name`
      configuration property.
      

[CAUTION]
====
If you set the `hibernate.session_factory_name` property in the Hibernate configuration
and you don't use JNDI, you will also have to set `hibernate.session_factory_name_is_jndi` to `false`.
====

==== CDI environment

You can use CDI to retrieve the `EntityManagerFactory`.
Unless you use an already packaged `hibernate-search-jsr352` module for your application container,
this will require you to add the `hibernate-search-jsr352-cdi` jar to your classpath.

If you use only one persistence unit, the mass indexer will be able to access
your database automatically without any special configuration.

If you want to use multiple persistence unit,
you will have to register those as beans in the CDI context.
Note that entity manager factories may not be considered as beans by default,
in which case you will have to register them yourself.
You may use an application-scoped bean to do so:

====
[source, JAVA]
----
@ApplicationScoped
public class EntityManagerFactoriesProducer {
	
	@PersistenceUnit(unitName = "db1")
	private EntityManagerFactory db1Factory;
	
	@PersistenceUnit(unitName = "db2")
	private EntityManagerFactory db2Factory;
	
	@Produces
	@Singleton
	@Named("db1") // The name to use when referencing the bean
	public EntityManagerFactory createEntityManagerFactoryForDb1() {
		return db1Factory;
	}
	
	@Produces
	@Singleton
	@Named("db2") // The name to use when referencing the bean
	public EntityManagerFactory createEntityManagerFactoryForDb2() {
		return db2Factory;
	}
}
----
====

Once the entity manager factories are registered in the CDI context,
you can instruct the mass indexer to use one in particular by naming it
using the `entityManagerReference` parameter.

[NOTE]
====
Due to limitations of the CDI APIs, it is not currently possible to reference
an entity manager factory by its persistence unit name when using the mass indexer with CDI.
====
