// SPDX-License-Identifier: Apache-2.0
// Copyright Red Hat Inc. and Hibernate Authors
[[binding-named-predicate]]
= [[mapper-orm-bridge-named-predicate]] Defining named predicates

include::../components/_incubating-warning.adoc[]

When implementing a <<binding-propertybridge,`PropertyBinder`>>
or <<binding-typebridge,`TypeBinder`>>,
it is possible to assign "named predicates"
to index schema elements (either the index root or an <<binding-index-field-dsl-object,object field>>).

These named predicates will then be usable <<search-dsl-predicate-named,through the Search DSL>>,
referencing them by name and optionally passing parameters.
The main point is that the implementation is hidden from callers:
they do not need to understand how data is indexed in order to use a named predicate.

Below is a simple example using the DSL to declare an object field and assign a named predicate to that field,
in a property binder.

.Declaring a named predicate
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/binding/namedpredicate/SkuIdentifierBinder.java[tags=binder]
----
<1> The binder defines a named predicate.
Note this predicate is assigned to an object field.
<2> The predicate name will be used to refer to this predicate when <<search-dsl-predicate-named,calling the named predicate>>.
Since the predicate is assigned to an object field,
callers will have to prefix the predicate name with the path to that object field.
<3> The predicate definition will define how to create the predicate when searching.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/binding/namedpredicate/SkuIdentifierBinder.java[tags=bridge]
----
<1> Here the bridge class is nested in the binder class,
because it is more convenient,
but you are obviously free to implement it as you wish:
as a lambda expression, in a separate Java file...
<2> The bridge creates an object to hold the various components of the SKU identifier.
<3> The bridge populates the various components of the SKU identifier.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/binding/namedpredicate/SkuIdentifierBinder.java[tags=predicate-definition]
----
<1> The predicate definition must implement the `PredicateDefinition` interface.
+
Here the predicate definition class is nested in the binder class,
because it is more convenient,
but you are obviously free to implement it in a separate java file.
<2> The context passed to the definition exposes the predicate factory,
which is the entry point to the <<search-dsl-predicate,predicate DSL>>,
used to create predicates.
<3> The definition can access parameters that are passed when calling the named predicates.
+
The `param` method will throw an exception if the parameter has not been defined.
Alternatively, use `paramOptional` to get an `java.util.Optional` that will be empty if the parameter has not been defined.
<4> The definition uses the predicate factory to create predicates.
In this example, this implementation transforms a pattern with a custom format into three patterns,
one for each field populated by the bridge.
<5> Be careful: the search predicate factory expects paths
relative to the object field where the named predicate was registered.
Here the path `departmentCode` will be understood as `<path to the object field>.departmentCode`.
See also <<search-dsl-paths>>.
<6> Do not forget to call `toPredicate()` to return a `SearchPredicate` instance.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/binding/namedpredicate/ItemStock.java[tags=include;!getters-setters]
----
<1> Apply the bridge using the `@PropertyBinding` annotation.
The predicate will be available in the Search DSL,
as shown in <<search-dsl-predicate-named>>.
====
