[[binding-projection]]
= Projection binder

[[binding-projection-basics]]
== Basics

NOTE: Projection binders are an advanced feature that application developers generally shouldn't need to bother with.
Before resorting to custom projection binders,
consider relying on <<mapping-projection-inner-explicit,explicit projection constructor parameter mapping>>
using built-in annotations such as <<search-dsl-projection-id-mapping,`@IdProjection`>>,
<<search-dsl-projection-field-mapping,`@FieldProjection`>>,
<<search-dsl-projection-object-mapping,`@ObjectProjection`>>, ...

A projection binder is a pluggable component that implements
the binding of a constructor parameter to a <<search-dsl-projection,projection>>.
It is applied to a parameter of a <<mapping-projection,projection constructor>>
with the `@ProjectionBinding` annotation
or with a <<mapping-custom-annotations,custom annotation>>.

The projection binder can inspect the constructor parameter,
and is expected to assign a projection definition to that constructor parameter,
so that whenever the <<mapping-projection,projection constructor>> is invoked,
Hibernate Search will pass the result of that projection through that constructor parameter.

Implementing a projection binder requires two components:

. A custom implementation of `ProjectionBinder`, to bind the projection definition to the parameter at bootstrap.
This involves inspecting the constructor parameter if necessary,
and instantiating the projection definition.
. A custom implementation of `ProjectionDefinition`, to instantiate the projection at runtime.
This involves using the <<search-dsl-projection,projection DSL>>
and returning the resulting `SearchProjection`.

Below is an example of a custom projection binder that binds
a parameter of type `String` to a projection to the `title` field in the index.

NOTE: A similar result can be achieved without a custom projection binder.
This is just to keep the example simple.

.Implementing and using a `ProjectionBinder`
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/simple/MyFieldProjectionBinder.java[tags=binder]
----
<1> The binder must implement the `ProjectionBinder` interface.
<2> Implement the `bind` method in the binder.
<3> Call `context.definition(...)` to define the projection to use.
<4> Pass the expected type of the constructor parameter.
<5> Pass the projection definition instance,
which will create the projection at runtime.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/simple/MyFieldProjectionBinder.java[tags=definition]
----
<1> Here the definition class is nested in the binder class,
because it is more convenient,
but you are obviously free to implement it as you wish:
as a lambda expression, in a separate Java file...
<2> The definition must implement the `ProjectionDefinition` interface.
One generic type argument must be provided: the type of the projected value,
i.e. the type of the constructor parameter.
<3> Use the provided `SearchProjectionFactory` and the <<search-dsl-projection,projection DSL>>
to define the appropriate projection.
<4> Get the resulting projection by calling `.toProjection()` and return it.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/simple/MyBookProjection.java[tags=include]
----
<1> Apply the binder using the `@ProjectionBinding` annotation.

The book projection can then be used as any <<search-dsl-projection-mapped,custom projection type>>,
and its `title` parameter will be initialized with values returned by the custom projection definition:

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/simple/ProjectionBinderSimpleIT.java[tags=call]
----
====

[[binding-projection-multi]]
== Multi-valued projections

include::../components/_incubating-warning.adoc[]

You can call `.multi()` on the context passed to the projection binder
in order to discover whether the constructor parameter being bound is multi-valued
(according to the same rules as <<mapping-projection-inner-inference-type,implicit inner projection inference>>),
and to bind a multi-valued projection.

.Implementing and using a `ProjectionBinder` supporting multi-valued projections
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/multi/MyFieldProjectionBinder.java[tags=include]
----
<1> `multi()` returns an optional that contains a context
if and only if the constructor parameter is considered multi-valued.
<2> Call `multi.definition(...)` to define the projection to use.
<3> Here we're failing for single-valued constructor parameters,
but we could theoreticall fall back to a single-valued projection.
<4> The projection definition, being multi-valued,
must implement `ProjectionDefinition<List<T>>`,
where `T` is the exepected type of projected values,
and must configure returned projections accordingly.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/multi/MyBookProjection.java[tags=include]
----
<1> Apply the binder using the `@ProjectionBinding` annotation.

The book projection can then be used as any <<search-dsl-projection-mapped,custom projection type>>,
and its `tags` parameter will be initialized with values returned by the custom projection definition:

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/multi/ProjectionBinderMultiIT.java[tags=call]
----
====

[[binding-projection-composing]]
== Composing projection constructors

include::../components/_incubating-warning.adoc[]

You can call `.createObjectDefinition( "someFieldPath", SomeType.class )` on the context passed to the projection binder
in order to retrieve the definition of an <<search-dsl-projection-object,object projection>>
based on the <<mapping-projection,projection constructor mapping>> of `SomeType`.

This effectively allows using projection constructors within projection binders,
simply by passing the resulting definition to `.definition(...)`
or by delegating to it in a custom projection definition.

Other methods exposed on the binding context work similarly:

* `.createObjectDefinitionMulti(...)` returns a <<binding-projection-multi,multi-valued>> object projection definition.
* `.createCompositeDefinition(...)` returns a (single-valued)
<<search-dsl-projection-composite,composite projection>> definition
(which, on contrary to an <<search-dsl-projection-object,object projection>>, is not bound to an object field in the index).

Below is an example using `.createObjectDefinition(...)` to delegate to another projection constructor.

NOTE: A similar result can be achieved without a custom projection binder,
simply by relying on <<mapping-projection-inner-inference,implicit inner projection inference>>
or by using <<search-dsl-projection-object-mapping,`@ObjectProjection`>>.
This is just to keep the example simple.

.Implementing and using a `ProjectionBinder` that delegates to a projection constructor
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/composing/MyObjectFieldProjectionBinder.java[tags=include]
----
<1> Call `createObjectDefinition(...)` to create a definition to delegate to.
<2> Pass the <<search-dsl-projection-object-syntax,name of the object field to project on>>.
<3> Pass the <<search-dsl-projection-object-as-mapped,projected type>>.
<4> Pass the filter for nested projections; here we're not filtering at all.
This controls the same feature as <<search-dsl-projection-object-mapping-filters,`includePaths`/`excludePaths`/`includeDepths` in `@ObjectProjection`>>.
<5> Call `definition(...)` and pass the definition created just above.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/composing/MyBookProjection.java[tags=include]
----
<1> Apply the binder using the `@ProjectionBinding` annotation.
<2> Make sure the projected type passed to `createObjectDefinition(...)` has a projection constructor.

The book projection can then be used as any <<search-dsl-projection-mapped,custom projection type>>,
and its `author` parameter will be initialized with values returned by the custom projection definition:

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/composing/ProjectionBinderComposingIT.java[tags=call]
----
====

[[binding-projection-parameters]]
== Passing parameters

There are two ways to pass parameters to property bridges:

* One is (mostly) limited to string parameters, but is trivial to implement.
* The other can allow any type of parameters, but requires you to declare your own annotations.

[[binding-projection-parameters-string]]
=== Simple, string parameters

You can pass string parameters to the `@ProjectionBinderRef` annotation and then use them later in the binder:

.Passing parameters to a `ProjectionBinder` using the `@ProjectionBinderRef` annotation
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/param/string/MyFieldProjectionBinder.java[tags=include]
----
<1> Use the binding context to get the parameter value.
+
The `param` method will throw an exception if the parameter has not been defined.
Alternatively, use `paramOptional` to get an `java.util.Optional` that will be empty if the parameter has not been defined.
<2> Pass the parameter value as an argument to the definition constructor.
<3> Use the parameter value in the projection definition.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/param/string/MyBookProjection.java[tags=include]
----
<1> Define the binder to use on the constructor parameter,
setting the `fieldName` parameter.
====

[[binding-projection-parameters-custom-annotation]]
=== Parameters with custom annotations

You can pass parameters of any type to the bridge by defining
a <<mapping-custom-annotations,custom annotation>> with attributes:

.Passing parameters to a `PropertyBinder` using a custom annotation
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/param/annotation/MyFieldProjectionBinding.java[tags=include]
----
<1> Define an annotation with `RUNTIME` retention.
*Any other retention policy will cause the annotation to be ignored by Hibernate Search*.
<2> Since we will be mapping a projection definition to a projection constructor,
allow the annotation to target method parameters (constructors are methods).
<3> Mark this annotation as a method parameter mapping,
and instruct Hibernate Search to apply the given processor whenever it finds this annotation.
It is also possible to reference the processor by its CDI/Spring bean name.
<4> Optionally, mark the annotation as documented,
so that it is included in the javadoc of your entities.
<5> Define an attribute of type `String` to specify the field name.
<6> Here the processor class is nested in the annotation class,
because it is more convenient,
but you are obviously free to implement it in a separate Java file.
<7> The processor must implement the `MethodParameterMappingAnnotationProcessor` interface,
setting its generic type argument to the type of the corresponding annotation.
<8> In the annotation processor, instantiate the binder.
<9> Process the annotation attributes and pass the data to the binder.
+
Here we're using a setter, but passing the data through the constructor would work, too.
<10> Apply the binder to the constructor parameter.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/param/annotation/MyFieldProjectionBinder.java[tags=include]
----
<1> Implement setters in the binder.
Alternatively, we could expose a parameterized constructor.
<2> In the `bind` method, use the value of parameters.
Here we pass the parameter value as an argument to the definition constructor.
<3> Use the parameter value in the projection definition.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/param/annotation/MyBookProjection.java[tags=include]
----
<1> Apply the binder using its custom annotation,
setting the `fieldName` parameter.
====

[[binding-projection-injecting-beans]]
== Injecting beans into the binder

With <<configuration-bean-frameworks,compatible frameworks>>,
Hibernate Search supports injecting beans into:

* the `MethodParameterMappingAnnotationProcessor` if you use <<binding-projection-parameters-custom-annotation,custom annotations>>.
* the `ProjectionBinder` if you use the <<binding-projection-basics,`@ProjectionBinding` annotation>>.

NOTE: This only applies to beans instantiated
through Hibernate Search's <<configuration-bean-resolution,bean resolution>>.
As a rule of thumb, if you need to call `new MyBinder()` explicitly at some point,
the binder won't get auto-magically injected.

The context passed to the property binder's `bind` method
also exposes a `beanResolver()` method to access the bean resolver and instantiate beans explicitly.

See <<configuration-bean-injection>> for more details.

[[binding-projection-programmatic]]
== Programmatic mapping

You can apply a projection binder through the <<mapping-programmatic,programmatic mapping>> too.
Just pass an instance of the binder to `.projection(...)`. You can pass arguments either through the binder's constructor, or through setters.

.Applying a `ProjectionBinder` with `.projection(...)`
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/param/annotation/ProjectionBinderParamAnnotationIT.java[tags=programmatic]
----
====

[[binding-projection-parameters-incubating]]
== Other incubating features

include::../components/_incubating-warning.adoc[]

The context passed to the projection binder's `bind` method
exposes a `constructorParameter()` method that gives access to metadata about the constructor parameter being bound.

The metadata can be used to inspect the constructor parameter in details:

* Getting the name of the constructor parameter.
* Checking the type of the constructor parameter.

Similarly, the <<binding-projection-multi,context used for multi-valued projection binding>>
exposes a `containerElement()` method that gives access to the type of elements
of the (multi-valued) constructor parameter type.

See the javadoc for more information.

[NOTE]
====
The name of the constructor parameter is only available:

* For the canonical constructor of record types, regardless of compiler flags.
* For constructors of non-record types or non-canonical constructors of record types
if and only if the type was compiled with the `-parameters` compiler flag.
====

Below is an example of the simplest use of this metadata,
getting the constructor parameter name and using it as a field name.

.Projecting on a field whose name is the same as the constructor parameter name in a `ProjectionBinder`
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/constructorparameter/MyFieldProjectionBinder.java[tags=include]
----
<1> Use the binding context to get the constructor parameter.
<2> Pass the name of the constructor parameter to the projection definition.
<3> Use the name of the constructor parameter as the projected field name.

[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedirJava17}/org/hibernate/search/documentation/mapper/orm/binding/projectionbinder/constructorparameter/MyBookProjection.java[tags=include]
----
<1> Apply the binder using the `@ProjectionBinding` annotation.
====
