[[binding-basics]]
= [[mapper-orm-bridge-basics]] [[section-custom-bridges]] Basics

In Hibernate Search, <<concepts-binding,binding>> is the process of assigning custom components to the domain model.

The most intuitive components that can be bound are bridges,
responsible for converting pieces of data from the entity model to the document model.

For example, when `@GenericField` is applied to a property of a custom enum type,
a built-in bridge will be used to convert this enum to a string when indexing,
and to convert the string back to an enum when projecting.

Similarly, when an entity identifier of type `Long` is mapped to a document identifier,
a built-in bridge will be used to convert the `Long` to a `String`
(since all document identifiers are strings)
when indexing,
and back from a `String` to a `Long` when loading search results.

Bridges are not limited to one-to-one mapping:
for example, the <<mapping-geopoint-geopointbinding,`@GeoPointBinding`>> annotation,
which maps two properties annotated with `@Latitude` and `@Longitude`
to a single field, is backed by another built-in bridge.

While built-in bridges are provided for a wide range of standard types,
they may not be enough for complex models.
This is why bridges are really useful:
it is possible to implement custom bridges and to refer to them in the Hibernate Search mapping.
Using custom bridges, custom types can be mapped,
even complex types that require user code to execute at indexing time.

There are multiple types of bridges,
detailed in the next sections.
If you need to implement a custom bridge, but don't quite know which type of bridge you need,
the following table may help:

[cols="h,1,1,1,1,1",options="header"]
.Comparison of available bridge types
|===
|Bridge type
|<<binding-valuebridge,`ValueBridge`>>
|<<binding-propertybridge,`PropertyBridge`>>
|<<binding-typebridge,`TypeBridge`>>
|<<binding-identifierbridge,`IdentifierBridge`>>
|<<binding-routingbridge,`RoutingBridge`>>

|Applied to...
|Class field or getter
|Class field or getter
|Class
|Class field or getter (usually entity ID)
|Class

|Maps to...
|One index field.
Value field only: integer, text, geopoint, etc.
No <<binding-index-field-dsl-object,object field>> (composite).
|One index field or more.
Value fields as well as <<binding-index-field-dsl-object,object fields>> (composite).
|One index field or more.
Value fields as well as <<binding-index-field-dsl-object,object fields>> (composite).
|Document identifier
|Route (conditional indexing, <<concepts-sharding-routing,routing key>>)

|Built-in annotation(s)
|<<mapping-directfieldmapping,`@GenericField`, `@FullTextField`, ...>>
|`@PropertyBinding`
|`@TypeBinding`
|<<mapping-identifiermapping,`@DocumentId`>>
|`@Indexed( routingBinder = ... )`

|Supports <<mapping-containerextractor,container extractors>>
|Yes
|No
|No
|No
|No

|Supports mutable types
|[red]*No*
|Yes
|Yes
|[red]*No*
|Yes
|===

Not all binders are about indexing, however.
The constructor parameters involved in <<mapping-projection,projection constructors>>
can be bound as well; you will find more information about that in <<binding-projection,this section>>.