// SPDX-License-Identifier: Apache-2.0
// Copyright Red Hat Inc. and Hibernate Authors
[[explicit-backend-index-operations-elasticsearch]]
= Elasticsearch-specific explicit backend/index operations

[[explicit-backend-index-operations-elasticsearch-access-client]]
== [[backend-elasticsearch-access-client]][[elasticsearch-client-access]] Retrieving the REST client

When writing complex applications with advanced requirements,
it may be necessary from time to time to send requests to the Elasticsearch cluster directly,
in particular if Hibernate Search does not support this kind of requests out of the box.

To that end, you can retrieve the Elasticsearch backend,
then get access the Elasticsearch client used by Hibernate Search internally.
See below for an example.

.Accessing the low-level REST client
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/backend/elasticsearch/client/ElasticsearchGetClientIT.java[tags=client]
----
<1> <<entrypoints-search-mapping,Retrieve the `SearchMapping`>>.
<2> Retrieve the `Backend`.
<3> Narrow down the backend to the `ElasticsearchBackend` type.
<4> Get the client, passing the expected type of the client as an argument.
====

[WARNING]
====
The client itself is not part of the Hibernate Search API,
but of the
link:{elasticsearchDocUrl}/index-modules.html#_static_index_settings[official Elasticsearch REST client API].

Hibernate Search may one day switch to another client with a different Java type,
without prior notice.
If that happens, the snippet of code above will throw an exception.
====