// SPDX-License-Identifier: Apache-2.0
// Copyright Red Hat Inc. and Hibernate Authors
[[listener-triggered-indexing]]
= [[indexing-automatic]] [[mapper-orm-indexing-automatic]] [[_automatic_indexing]] Implicit, listener-triggered indexing

[[listener-triggered-indexing-concepts]]
== [[indexing-automatic-concepts]][[mapper-orm-indexing-automatic-concepts]] Basics

include::../components/_mapper-orm-only-note.adoc[]

By default, every time an entity is changed through a Hibernate ORM Session,
if the <<concepts-entity,entity type>> is <<mapping-entityindexmapping,mapped to an index>>,
Hibernate Search updates the relevant index transparently.

Here is how listener-triggered indexing works at a high level:

1. When the Hibernate ORM `Session` gets flushed (explicitly or as part of a transaction commit),
Hibernate ORM determines what changed exactly (entity created, updated, deleted),
forwards the information to Hibernate Search.
2. Hibernate Search adds this information to a (session-scoped) <<indexing-plan,indexing plan>>
and the plan processes change events added so far,
either inferring which entities need to be reindexed and building the corresponding documents (<<coordination-none,no coordination>>)
or building events to be sent to the outbox (<<coordination-outbox-polling,`outbox-polling` coordination>>).
3. On database transaction commit, the plan gets executed,
either sending the document indexing/deletion request to the backend (<<coordination-none,no coordination>>)
or sending the events to the database (<<coordination-outbox-polling,`outbox-polling` coordination>>).

Below is a summary of key characteristics of listener-triggered indexing
and how they vary depending on the configured <<coordination,coordination strategy>>.

Follow the links for more details.

[cols="h,2*^",options="header"]
.Comparison of listener-triggered indexing depending on the coordination strategy
|===
|Coordination strategy
|<<coordination-none,No coordination>> (default)
|<<coordination-outbox-polling,Outbox polling>>

|Detects changes occurring in ORM sessions (`session.persist(...)`, `session.delete(...)`, setters, ...)
2+|<<indexing-automatic-concepts-changes-in-session,Yes>>

|Detects changes caused by JPQL or SQL queries (`insert`/`update`/`delete`)
2+|<<limitations-changes-in-session,No>>

|Associations must be updated on both sides
2+|<<limitations-changes-asymmetric-association-updates,Yes>>

|Changes triggering reindexing
2+|<<indexing-automatic-concepts-dirty-checking,Only relevant changes>>

|Guarantee of indexes updates
|<<coordination-none-indexing-guarantee,Non-transactional, after the database transaction / `SearchSession.close()` returns>>
|<<coordination-outbox-polling-indexing-guarantee,Transactional, on database transaction commit>>

|Visibility of index updates
|<<coordination-none-indexing-visibility,Configurable: immediate (poor performance) or eventual>>
|<<coordination-outbox-polling-indexing-visibility,Eventual>>

|Overhead for application threads
|<<coordination-none-indexing-on-flush,Low to medium>>
|<<coordination-outbox-polling-indexing-background,Very low>>

|Overhead for the database
|<<coordination-none-indexing-lazy-loading,Low>>
|<<coordination-outbox-polling-indexing-full-loading,Low to medium>>
|===

[[indexing-automatic-configuration]]
== [[mapper-orm-indexing-automatic-configuration]] Configuration

Listener-triggered indexing may be unnecessary if your index is read-only
or if you update it regularly by reindexing,
either using the <<indexing-massindexer,`MassIndexer`>>,
using the <<mapper-orm-indexing-jakarta-batch,Jakarta Batch mass indexing job>>,
or <<indexing-explicit,explicitly>>.

You can disable listener-triggered indexing by setting the configuration property
`hibernate.search.indexing.listeners.enabled` to `false`.

As listener-triggered indexing uses <<indexing-plan,indexing plans>> under the hood,
several configuration options affecting indexing plans will affect listener-triggered indexing as well:

* The <<indexing-plan-synchronization,indexing plan synchronization strategy>>.
* The <<indexing-plan-filter,indexing plan filter>>.

[[indexing-automatic-concepts-changes-in-session]]
== [[mapper-orm-indexing-automatic-concepts-changes-in-session]] In-session entity change detection and limitations

Hibernate Search uses internal events of Hibernate ORM in order to detect changes.
These events will be triggered if you actually manipulate managed entity objects in your code:
calls to `session.persist(...)`, `session.delete(...)`, to entity setters, etc.

This works great for most applications, but you need to consider some limitations:

* <<limitations-changes-in-session>>
* <<limitations-changes-asymmetric-association-updates>>

[[indexing-automatic-concepts-dirty-checking]]
== [[mapper-orm-indexing-automatic-concepts-dirty-checking]] Dirty checking
Hibernate Search is aware of the entity properties that are accessed when building indexed documents.
When processing Hibernate ORM entity change events, it is also aware of which properties actually changed.
Thanks to that knowledge, it is able to detect which entity changes are actually relevant to indexing,
and to skip reindexing when a property is modified, but does not affect the indexed document.
