// SPDX-License-Identifier: Apache-2.0
// Copyright Red Hat Inc. and Hibernate Authors
[[integrations]]
= Standards and integrations

[[other-integrations-jakarta]]
== Jakarta EE

Hibernate Search targets link:{jakartaUrl}[Jakarta EE] where relevant,
in particular Jakarta Persistence {jakartaPersistenceVersion} with the <<mapper-orm,Hibernate ORM Mapper>>.

[[other-integrations-javaee]]
== Java EE

Hibernate Search no longer supports link:{javaeeUrl}[Java EE].

Use <<other-integrations-jakarta,Jakarta EE>> instead.

[[other-integrations-orm6]]
== [[other-integrations-orm5]] Hibernate ORM 6/5

The Hibernate Search {hibernateSearchVersionShort} series is no longer compatible with Hibernate ORM 6 and 5.
It targets the Hibernate ORM 7 series.
Check the https://hibernate.org/search/releases/#compatibility-matrix[compatibility matrix]
to find versions of Hibernate Search compatible with these older versions of Hibernate ORM.

Use <<other-integrations-jakarta,Hibernate ORM 7>> instead.

[[other-integrations-lucene-next]]
== Lucene 10

Hibernate Search {hibernateSearchVersionShort} provides two variations of the <<backend-lucene,Lucene backend>>.

The default one, that works with JDK 17+ and uses Lucene {luceneVersion}:

[source, XML, subs="+attributes"]
----
<dependency>
    <groupId>org.hibernate.search</groupId>
    <artifactId>hibernate-search-backend-lucene</artifactId>
</dependency>
----

And the Lucene {luceneNextVersion} based one, that requires JDK 21+:

[source, XML, subs="+attributes"]
----
<dependency>
    <groupId>org.hibernate.search</groupId>
    <artifactId>hibernate-search-backend-lucene-next</artifactId>
</dependency>
----
