// SPDX-License-Identifier: Apache-2.0
// Copyright Red Hat Inc. and Hibernate Authors
[[integrations]]
= Standards and integrations

[[other-integrations-jakarta]]
== Jakarta EE

Hibernate Search targets link:{jakartaUrl}[Jakarta EE] where relevant,
in particular Jakarta Persistence {jakartaPersistenceVersion} with the <<mapper-orm,Hibernate ORM Mapper>>.

[[other-integrations-javaee]]
== Java EE

Hibernate Search no longer supports link:{javaeeUrl}[Java EE].

Use <<other-integrations-jakarta,Jakarta EE>> instead.

[[other-integrations-orm6]]
== [[other-integrations-orm5]] Hibernate ORM 6/5

The Hibernate Search {hibernateSearchVersionShort} series is no longer compatible with Hibernate ORM 6 and 5.
It targets the Hibernate ORM 7 series.
Check the https://hibernate.org/search/releases/#compatibility-matrix[compatibility matrix]
to find versions of Hibernate Search compatible with these older versions of Hibernate ORM.

Use <<other-integrations-jakarta,Hibernate ORM 7>> instead.

[[other-integrations-lucene-next]]
== Lucene 10

include::../components/_incubating-warning.adoc[]

Hibernate Search {hibernateSearchVersionShort} provides two variants of the <<backend-lucene,Lucene backend>>.

The default, stable one, that works with JDK 17+ and uses Lucene {luceneVersion}:

[source, XML, subs="+attributes"]
----
<dependency>
    <groupId>org.hibernate.search</groupId>
    <artifactId>hibernate-search-backend-lucene</artifactId>
</dependency>
----

And an incubating one based on Lucene {luceneNextVersion}, that requires JDK 21+:

[source, XML, subs="+attributes"]
----
<dependency>
    <groupId>org.hibernate.search</groupId>
    <artifactId>hibernate-search-backend-lucene-next</artifactId>
</dependency>
----

[NOTE]
====
`hibernate-search-backend-lucene-next` is tested against the same test suite as `hibernate-search-backend-lucene`
and currently provides the same search capabilities. The main difference is the Lucene version backing it.
While Hibernate Search {hibernateSearchVersionShort} still <<compatibility-dependencies,targets>> JDK 17,
Lucene, starting with version 10, is leveraging new Java APIs, particularly to work with memory, that are available starting with JDK 21.
For users running their applications on JDK 21+ and wanting to get the latest Lucene improvements, it would be beneficial to
use this new backend.
====
