// SPDX-License-Identifier: Apache-2.0
// Copyright Red Hat Inc. and Hibernate Authors
[[limitations]]
= [[elasticsearch-limitations]] Known issues and limitations

[[limitations-parallel-embedded-update]]
== Without coordination, in rare cases, indexing involving `@IndexedEmbedded` may lead to out-of sync indexes
// TODO: we might what to better explain "indexing" in the title ^ which is talking about architecture-hsearch-indexing

[[limitations-parallel-embedded-update-description]]
=== Description

With the default settings (<<coordination-none,no coordination>>),
if two entity instances are <<mapping-indexedembedded,indexed-embedded>> in the same "index-embedding" entity,
and these two entity instance are updated in parallel transactions,
there is a small risk that the transaction commits happen in just the wrong way,
leading to the index-embedding entity being re-indexed with only part of the updates.

For example, consider indexed entity A, which index-embeds B and C.
The following course of events involving two parallel transactions (T1 and T2)
will lead to an out of date index:

* T1: Load B.
* T1: Change B in a way that will require reindexing A.
* T2: Load C.
* T2: Change C in a way that will require reindexing A.
* T2: Request the transaction commit.
  Hibernate Search builds the document for A.
  While doing so, it automatically loads B. B appears unmodified, as T1 wasn't committed yet.
* T1: Request the transaction commit.
  Hibernate Search builds documents to index.
  While doing so, it automatically loads C. C appears unmodified, as T2 wasn't committed yet.
* T1: Transaction is committed.
  Hibernate Search automatically sends the updated A to the index.
  In this version, B is updated, but C is not.
* T2: Transaction is committed.
  Hibernate Search automatically sends the updated A to the index.
  In this version, C is updated, but B is not.

This chain of events ends with the index containing a version of A where C is updated, but B is not.

[[limitations-parallel-embedded-update-solution]]
=== Solutions and workarounds

The following solutions can help circumvent this limitation:

1. Use a safer <<coordination,coordination strategy>>,
e.g. the <<coordination-outbox-polling,`outbox-polling` coordination strategy>>.
See in particular <<architecture-examples>>.
2. OR avoid parallel updates to entities that are indexed-embedded in the same indexed entity.
This is only possible in very specific setups.
3. OR schedule a <<indexing-massindexer,full reindexing>> of your database periodically (e.g. every night)
to get the index back in sync with the database.

[[limitations-parallel-embedded-update-roadmap]]
=== Roadmap

This limitation is caused directly by the lack of coordination between threads or application nodes,
so it can only be addressed completely by configuring <<coordination,coordination>>.

There are no other solutions currently on the roadmap.

[[limitations-backend-indexing-error]]
== Without coordination, backend errors during indexing may lead to out-of sync indexes

[[limitations-backend-indexing-error-description]]
=== Description

With the default settings (<<coordination-none,no coordination>>),
<<architecture-hsearch-indexing,indexing>>
will actually apply index changes in the backend *just after* the transaction commit,
without any kind of transaction log for the index changes.

Consequently, should an error occur in the backend while indexing (i.e. an I/O error),
this indexing will be cancelled, with no way to cancel the corresponding database transaction:
the index will thus become out of sync.

NOTE: The risk is exclusively related to errors in the backend, mostly to filesystem or network issues.
Errors occurring in user code (getters, custom <<binding,bridges>>, ...)
will safely cancel the whole database transaction without indexing anything,
ensuring that indexes are still in sync with the database.

[[limitations-backend-indexing-error-solution]]
=== Solutions and workarounds

The following solutions can help circumvent this limitation:

1. Use a safer <<coordination,coordination strategy>>,
e.g. the <<coordination-outbox-polling,`outbox-polling` coordination strategy>>.
See in particular <<architecture-examples>>.
2. OR schedule a <<indexing-massindexer,full reindexing>> of your database periodically (e.g. every night)
to get the index back in sync with the database.

[[limitations-backend-indexing-error-roadmap]]
=== Roadmap

This limitation is caused directly by the lack of persistence of entity change events,
so it can only be addressed completely by persisting those events,
e.g. by switching to the <<coordination-outbox-polling,`outbox-polling` coordination strategy>>.

Some incomplete countermeasures may be considered in future versions,
such as automatic in-thread retries,
but they will never solve the problem completely,
and they are not currently on the roadmap.

[[limitations-changes-in-session]]
== Listener-triggered indexing only considers changes applied directly to entity instances in Hibernate ORM sessions

[[limitations-changes-in-session-description]]
=== Description

Due to <<indexing-automatic-concepts-changes-in-session,how Hibernate Search uses internal events of Hibernate ORM>>
in order to detect changes,
it will not detect changes resulting from `insert`/`delete`/`update` queries,
be it SQL or JPQL/HQL queries.

This is because queries are executed on the database side,
without Hibernate ORM or Search having any knowledge of which entities are actually created, deleted or updated.

[[limitations-changes-in-session-solution]]
=== Solutions and workarounds

One workaround is to reindex explicitly after you run JPQL/SQL queries,
either using the <<indexing-massindexer,`MassIndexer`>>,
using the <<mapper-orm-indexing-jakarta-batch,Jakarta Batch mass indexing job>>,
or <<indexing-explicit,explicitly>>.

[[limitations-changes-in-session-roadmap]]
=== Roadmap

One solution to actually detect these changes would be to source entity change events
directly from the database, using for example Debezium.

This is tracked as https://hibernate.atlassian.net/browse/HSEARCH-3513[HSEARCH-3513],
but is long-term goal.

[[limitations-changes-asymmetric-association-updates]]
== [[mapper-orm-indexing-automatic-concepts-session-consistency]] Listener-triggered indexing ignores asymmetric association updates

[[limitations-changes-asymmetric-association-updates-description]]
=== Description

Hibernate ORM is able to handle asymmetric updates of associations,
where only the owning side of association is updated and the other side is ignored.
The entities in the session will be inconsistent for the duration of the session,
but upon reloading they will be consistent once again,
due to how entity loading works.

This practice of asymmetric updates of associations
can cause problems in applications in general,
but also in Hibernate Search specifically,
where it may lead to out-of-sync indexes.
Thus, it must be avoided.

For example, let's assume an indexed entity `A` has an `@IndexedEmbedded` association `A.b` to entity `B`,
and that `B` owns that association on its side, `B.a`.
One can just set `B.a` to `null` in order to remove the association between `A` and `B`,
and the effect on the database will be exactly what we want.

However, Hibernate Search will only be able to detect that `B.a` changed,
and by the time it tries to infer which entities need to be re-indexed,
it will no longer be able to know what `B.a` used to refer to.
That change in itself is useless to Hibernate Search:
Hibernate Search will not know that `A`, specifically, needs to be re-indexed.
It will "forget" to reindex `A`, leading to an out-of-sync index where `A.b` still contains `B`.

In the end, the only way for Hibernate Search to know that `A` needs to be re-indexed
is to also set `A.b` to `null`, which will cause Hibernate Search to detect that `A.b` changed,
and thus that `A` changed too.

[[limitations-changes-asymmetric-association-updates-solution]]
=== Solutions and workarounds

The following solutions can help circumvent this limitation:

1. When you update one side of an association,
always update the other side consistently.
2. When the above is not possible,
reindex affected entities explicitly after the association update,
either using the <<indexing-massindexer,`MassIndexer`>>,
using the <<mapper-orm-indexing-jakarta-batch,Jakarta Batch mass indexing job>>,
or <<indexing-explicit,explicitly>>.

[[limitations-changes-asymmetric-association-updates-roadmap]]
=== Roadmap

Hibernate Search may handle asymmetric association updates in the future,
by keeping tracks of entities added to / removed from an association.
However, this will only solve the problem completely if indexing happens asynchronously in a background thread,
such as with the <<coordination-outbox-polling,`outbox-polling` coordination strategy>>.
This is tracked as https://hibernate.atlassian.net/browse/HSEARCH-3567[HSEARCH-3567].

Alternatively, sourcing entity change events directly from the database, using for example Debezium,
would also solve the problem.
This is tracked as https://hibernate.atlassian.net/browse/HSEARCH-3513[HSEARCH-3513],
but is long-term goal.

[[limitations-indexing-plan-serialization]]
== Listener-triggered indexing is not compatible with `Session` serialization

[[limitations-indexing-plan-serialization-description]]
=== Description

When <<listener-triggered-indexing,listener-triggered indexing>> is enabled,
Hibernate Search collects entity change events
to build an "indexing plan" inside the ORM `EntityManager`/`Session`.
The indexing plan holds information relative to which entities need to be re-indexed,
and sometimes documents that have not been indexed yet.

The indexing plan cannot be serialized.

If the ORM `Session` gets serialized,
all collected change events will be lost upon deserializing the session,
and Hibernate Search will likely "forget" to reindex some entities.

This is fine in most applications, since they do not rely on serializing the session,
but it might be a problem with some JEE applications relying on Bean Passivation.

[[limitations-indexing-plan-serialization-solution]]
=== Solutions and workarounds

Avoid serializing an ORM `EntityManager`/`Session` after changing entities.

[[limitations-indexing-plan-serialization-roadmap]]
=== Roadmap

There are no plans to address this limitation.
We do not intend to support `Session` serialization when Hibernate Search is enabled.
