// SPDX-License-Identifier: Apache-2.0
// Copyright Red Hat Inc. and Hibernate Authors
[[mapper-pojo-standalone]]
= Standalone POJO Mapper

include::../components/_incubating-warning.adoc[]

[[mapper-pojo-standalone-basics]]
== Basics

The Standalone POJO <<architecture-hsearch-components-mapper,Mapper>> enables mapping arbitrary POJOs to indexes.

Its key feature compared to the <<mapper-orm,Hibernate ORM integration>>
is its ability to run without Hibernate ORM or a relational database.

It can be used to index entities coming from an arbitrary datastore
or even (though that's not recommended in general)
to use Lucene or Elasticsearch as a primary datastore.

Because the Standalone POJO Mapper does not assume anything about the entities being mapped,
beyond the fact they are represented as POJOs,
it can be more complex to use than the <<mapper-orm,Hibernate ORM integration>>.
In particular:

* This mapper <<mapper-pojo-standalone-indexing-listener-triggered,cannot detect entity changes on its own>>:
all indexing <<mapper-pojo-standalone-indexing-plan,must be explicit>>.
* Loading of entities as hits in the result of a <<search-dsl-query,search query>>
must be <<mapper-pojo-standalone-search-query-loading,implemented in the application>>.
* Loading of identifiers and entities for <<indexing-massindexer,mass indexing>>
must be <<mapper-pojo-standalone-indexing-massindexer,implemented in the application>>.
* This mapper <<mapper-pojo-standalone-coordination,does not provide coordination between nodes>>
at the moment.

[[mapper-pojo-standalone-startup]]
== Startup

Starting up Hibernate Search with the Standalone POJO Mapper is explicit and involves a builder:

.Starting up Hibernate Search with the Standalone POJO Mapper
====
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/pojo/standalone/entrypoints/StandalonePojoEntryPointsIT.java[tags=setup]
----
<1> Create a builder, passing an `AnnotatedTypeSource` to let Hibernate Search know where to look for annotations.
<2> Set additional configuration properties (see also <<configuration>>).
<3> Build the `SearchMapping`.
====

[TIP]
====
Thanks to <<mapping-classpath-scanning,classpath scanning>>,
your `AnnotatedTypeSource` only needs to include one class
from each JAR containing annotated types.
Other types should be automatically discovered.

See also <<mapping-classpath-scanning-faster,this section>>
to troubleshoot or improve performance of classpath scanning.
====

[[mapper-pojo-standalone-shutdown]]
== Shutdown

You can shut down Hibernate Search with the Standalone POJO Mapper by calling the `close()` method on the mapping:

.Shutting down Hibernate Search with the Standalone POJO Mapper
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/pojo/standalone/entrypoints/StandalonePojoEntryPointsIT.java[tags=shutdown]
----
<1> Retrieve the `SearchMapping` that was returned when <<mapper-pojo-standalone-startup,Hibernate Search started>>.
<2> Call `close()` to shut down Hibernate Search.
====

On shutdown, Hibernate Search will stop accepting new indexing requests:
new indexing attempts will throw exceptions.
The `close()` method will only return once all ongoing indexing operations complete.

[[mapper-pojo-standalone-beanprovider]]
== Bean provider

include::../components/_incubating-warning.adoc[]

The Standalone POJO Mapper can <<configuration-bean,retrieve beans from CDI/Spring>>,
but that support needs to be implemented explicitly through a bean provider.

You can plug in your own bean provider in two steps:

. Define a class that implements the `org.hibernate.search.engine.environment.bean.spi.BeanProvider` interface.
. Configure Hibernate Search to use that implementation by setting the configuration property
`hibernate.search.bean_provider`
to a <<configuration-bean-reference-parsing,bean reference>> pointing to the implementation,
for example `class:com.mycompany.MyMappingConfigurer`.
Obviously, the reference to the bean provider cannot be resolved using the bean provider.

[[mapper-pojo-standalone-multi-tenancy]]
== Multi-tenancy

Multi-tenancy needs to be enabled explicitly when starting the Standalone POJO Mapper:

.Enabling multi-tenancy with the Standalone POJO Mapper
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/pojo/standalone/multitenancy/StandalonePojoMultiTenancyIT.java[tags=setup]
----
<1> Create a builder.
<2> Enable multi-tenancy.
<3> Build the `SearchMapping`.
====

Once multi-tenancy is enabled, a tenant ID will have to be provided when creating a `SearchSession` and in some other cases
(creating a <<indexing-massindexer,mass indexer>>, a <<indexing-workspace,workspace>>, ...).

.Creating the `SearchSession` with a tenant identifier
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/pojo/standalone/multitenancy/StandalonePojoMultiTenancyIT.java[tags=searchSession]
----
<1> <<entrypoints-search-mapping-mapper-pojo-standalone,Retrieve the `SearchMapping`>>.
<2> Start creating a new session.
<3> Set the tenant identifier for the new session.
<4> Build the new session.
====

[NOTE]
====
When using non-string tenant identifiers, a custom `TenantIdentifierConverter` must be provided:

[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/pojo/standalone/multitenancy/StandalonePojoMultiTenancyUuidIT.java[tags=setup]
----
<1> Create a builder.
<2> Enable multi-tenancy.
<3> Set a custom tenant identifier converter.
<4> Build the `SearchMapping`.
====


[[mapper-pojo-standalone-mapping]]
== Mapping

While the <<mapper-orm,Hibernate ORM integration>> can infer parts of the mapping from the Hibernate ORM mapping,
the Standalone POJO Mapper cannot.
As a result, the Standalone POJO Mapper needs more explicit configuration
for its mapping:

* <<concepts-entity,Entity types>> must be <<mapping-entitydefinition-explicit,defined explicitly>>.
* Document identifiers must be <<mapping-identifiermapping-explicit,mapped explicitly>>.
* The inverse side of associations must be <<mapping-reindexing-associationinverseside,mapped explicitly>>.

[[mapper-pojo-standalone-indexing]]
== Indexing

[[mapper-pojo-standalone-indexing-listener-triggered]]
=== [[mapper-pojo-standalone-indexing-automatic]] Listener-triggered indexing

The Standalone POJO Mapper does not provide "implicit" indexing
similar to the <<listener-triggered-indexing,listener-triggered indexing>> in the <<mapper-orm,Hibernate ORM integration>>.

Instead, you must index explicitly with an <<mapper-pojo-standalone-indexing-plan,indexing plan>>.

[[mapper-pojo-standalone-indexing-plan]]
=== Explicitly indexing on entity change events

The Standalone POJO Mapper can process entity change events (add, update, delete)
and perform indexing accordingly,
though events must necessarily be passed to Hibernate Search explicitly.
See <<indexing-plan>> for more information about the API.

One major difference with the <<mapper-orm,Hibernate ORM integration>>
is that transactions (JTA or otherwise are not supported),
so indexing is executed on <<entrypoints-search-session-mapper-pojo-standalone,session closing>>
rather than on transaction commit.

[[mapper-pojo-standalone-indexing-massindexer]]
=== Mass indexing

Because by default, the Standalone POJO Mapper does not know anything about where the entity data comes from,
<<indexing-massindexer,mass indexing>> requires plugging in a way to load entities _en masse_ from the other datastore:
a mass loading strategy.

Mass loading strategies are assigned to <<concepts-entity,entity types>>
as part of the <<mapping-entitydefinition,entity definition>>:
see <<mapping-entitydefinition-loading-mass>> for more information.

[[mapper-pojo-standalone-search-query-loading]]
=== Entity loading in search queries

Because by default, the Standalone POJO Mapper does not know anything about where the entity data comes from,
<<search-dsl-query-generality,entity loading in search queries>>
requires plugging in a way to load a selection of entities from the other datastore:
a selection loading strategy.

Selection loading strategies are assigned to <<concepts-entity,entity types>>
as part of the <<mapping-entitydefinition,entity definition>>:
see <<mapping-entitydefinition-loading-selection>> for more information.

[TIP]
====
With the Standalone POJO Mapper, if you want entities to be loaded from the index,
instead of an external datasource,
add a <<mapping-projection,projection constructor>> to your entity type.

This will automatically result in your entity being loaded from the index
when the configuration described in this section is missing and loading is required
(for example when not using `select()` in a search query).
====

[[mapper-pojo-standalone-coordination]]
== Coordination

The Standalone POJO Mapper does not provide any way
to coordinate between nodes at the moment,
so its behavior is roughly similar to that described in <<coordination-none>>,
except entity data extracting happens on session closing instead of happening on Hibernate ORM session flushes,
and indexing happens immediately after that instead of happening on transaction commit.

[[mapper-pojo-standalone-configuration-from-property-file]]
== Reading configuration properties from a file

The Standalone POJO Mapper `SearchMappingBuilder` can also take properties from a `Reader` compatible with `java.util.Properties#load(Reader)`:

.Loading configuration properties from a file using a `Reader`
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/pojo/standalone/entrypoints/StandalonePojoReadPropertiesFromFileIT.java[tags=setup]
----
<1> Get a reader representing a property file with configuration properties.
<2> Start configuring the Standalone POJO Mapper.
<3> Pass the property file reader to the builder.
====

[[mapper-pojo-standalone-configuration-other]]
== Other configuration

Other configuration properties are mentioned in the relevant parts of this documentation.
You can find a full reference of available properties in
<<configuration-properties-aggregated-hibernate-search-mapper-pojo-standalone, the Standalone POJO Mapper configuration properties appendix>>.
