[[mapping-configuration]]
= [[mapper-orm-mapping-configuration-mapping]] [[_configuring_the_mapping]] Configuring the mapping

[[mapping-annotations]]
== Annotation-based mapping

The main way to map entities to indexes is through annotations,
as explained in <<mapping-entityindexmapping>> and the following sections.

By default, Hibernate Search will automatically process mapping annotations for entity types,
as well as nested types in those entity types, for instance embedded types.

Annotation-based mapping can be disabled by setting `hibernate.search.mapping.process_annotations` to `false`
for the <<mapper-orm,Hibernate ORM integration>>,
or through `AnnotationMappingConfigurationContext` for any mapper:
see <<mapping-configurer>> to access that context,
and see the javadoc of `AnnotationMappingConfigurationContext` for available options.

[TIP]
====
If you disable annotation-based mapping, you will probably need to configure the mapping programmatically:
see <<mapping-programmatic>>.
====

Hibernate Search will also try to find some annotated types through <<mapping-classpath-scanning,classpath scanning>>.

[TIP]
====
See <<mapping-entityindexmapping>> and <<mapping-directfieldmapping>>
to get started with annotation-based mapping.
====

[[mapping-classpath-scanning]]
== [[mapper-orm-mapping-configuration-scanning]] Classpath scanning

[[mapping-classpath-scanning-basics]]
=== [[mapper-orm-mapping-configuration-scanning-basics]] Basics

Hibernate Search will automatically scan the JARs of entity types on startup,
looking for types annotated with "root mapping annotations"
so that it can automatically add those types to the list of types whose annotations should be processed.

Root mapping annotations are mapping annotations that serve as the entrypoint to a mapping,
for example <<mapping-projection,`@ProjectionConstructor`>>
or <<mapping-custom-annotations-root,custom root mapping annotations>>.
Without this scanning, Hibernate Search would learn about e.g. projection constructors too late
(when the projection is actually executed) and would fail due to a lack of metadata.

The scanning is backed by https://github.com/wildfly/jandex[Jandex], a library that indexes the content of JARs.

[[mapping-classpath-scanning-dependencies]]
=== [[mapper-orm-mapping-configuration-scanning-dependencies]] Scanning dependencies of the application

By default, Hibernate Search will only scan the JARs containing your Hibernate ORM entities.

If you want Hibernate Search to detect types annotated
with <<mapping-classpath-scanning-basics,root mapping annotations>> in other JARs,
you will first need to <<mapping-configurer,access an `AnnotationMappingConfigurationContext`>>.

From that context, either:

* call `annotationMappingContext.add( MyType.class )` to explicitly tell Hibernate Search
to process annotation on `MyType`, and to discover other types annotated with
<<mapping-classpath-scanning-basics,root mapping annotations>> in the JAR containing `MyType`.
* OR (advanced usage, incubating) call `annotationMappingContext.addJandexIndex( <an IndexView instance> )` to explicitly tell Hibernate Search
to look for types annotated with
<<mapping-classpath-scanning-basics,root mapping annotations>> in the given Jandex index.

[[mapping-classpath-scanning-faster]]
=== [[mapper-orm-mapping-configuration-scanning-faster]] Faster scanning

Hibernate Search's scanning may trigger the indexing of JARs through Jandex on application startup.
This indexing should be reasonably short, but if it causes performance issues, you can:

* Switch to the <<compatibility-framework-quarkus,Quarkus>> framework,
which among other things executes this part of Hibernate Search's startup at build time.
* OR execute the https://github.com/wildfly/jandex-maven-plugin[Jandex Maven Plugin]
during the build of your application, so that indexes are already built when the application starts.
* OR instruct Hibernate Search to never build Jandex indexes on startup,
by setting the configuration property
`hibernate.search.mapping.build_missing_discovered_jandex_indexes` to `false`.
**This is not recommended as it may lead to bootstrap failures or ignored mapping annotations**
because Hibernate Search will no longer be able to automatically discover types annotated with
<<mapping-classpath-scanning-basics,root annotations>>
in JARs that do not have an embedded Jandex index.

[[mapping-programmatic]]
== [[mapper-orm-programmatic-mapping]] [[mapper-orm-programmatic-mapping-basics]] [[hsearch-mapping-programmaticapi]] Programmatic mapping

Most examples in this documentation use annotation-based mapping,
which is generally enough for most applications.
However, some applications have needs that go beyond what annotations can offer:

* a single entity type must be mapped differently for different deployments -- e.g. for different customers.
* many entity types must be mapped similarly, without code duplication.

To address those needs, you can use _programmatic_ mapping:
define the mapping through code that will get executed on startup.

Programmatic mapping is configured through `ProgrammaticMappingConfigurationContext`:
see <<mapping-configurer>> to access that context.

[TIP]
====
By default, programmatic mapping will be merged with annotation mapping (if any).

To disable annotation mapping, see <<mapping-annotations>>.
====

[NOTE]
====
Programmatic mapping is declarative and exposes the exact same features as annotation-based mapping.

In order to implement more complex, "imperative" mapping,
for example to combine two entity properties into a single index field,
use <<binding,custom bridges>>.
====

[TIP]
====
Alternatively, if you only need to repeat the same mapping for several types or properties,
you can apply a custom annotation on those types or properties,
and have Hibernate Search execute some programmatic mapping code when it encounters that annotation.
This solution doesn't require mapper-specific configuration.

See <<mapping-custom-annotations>> for more information.
====

[[mapping-configurer]]
== Mapping configurer

[[mapper-orm-mapping-configurer]]
=== Hibernate ORM integration

With the Hibernate ORM integration, a custom `HibernateOrmSearchMappingConfigurer` can be plugged into Hibernate Search in order to configure
annotation mapping (`AnnotationMappingConfigurationContext`),
programmatic mapping (`ProgrammaticMappingConfigurationContext`), and more.

Plugging in a custom configurer requires two steps:

. Define a class that implements the `org.hibernate.search.mapper.orm.mapping.HibernateOrmSearchMappingConfigurer` interface.
. Configure Hibernate Search to use that implementation by setting the configuration property
`hibernate.search.mapping.configurer`
to a <<configuration-bean-reference-parsing,bean reference>> pointing to the implementation,
for example `class:com.mycompany.MyMappingConfigurer`.

TIP: You can pass multiple bean references separated by commas. See <<configuration-property-types>>.

Hibernate Search will call the `configure` method of this implementation on startup,
and the configurer will be able to take advantage of a DSL to define
the programmatic mapping, for example:

.Implementing a mapping configurer
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/programmatic/simple/MySearchMappingConfigurer.java[tags=include]
----
<1> Access the programmatic mapping.
<2> Access the programmatic mapping of type `Book`.
<3> Define `Book` as <<mapping-entityindexmapping-programmatic,indexed>>.
<4> Access the programmatic mapping of property `title` of type `Book`.
<5> Define an <<mapping-directfieldmapping-programmatic,index field>> based on property `title` of type `Book`.
====

[[mapper-pojo-standalone-mapping-configurer]]
=== Standalone POJO Mapper

The Standalone POJO Mapper does not offer a "mapping configurer" at the moment
(https://hibernate.atlassian.net/browse/HSEARCH-4615[HSEARCH-4615]).
However, `AnnotationMappingConfigurationContext`
and `ProgrammaticMappingConfigurationContext`
can be accessed when building the `SearchMapping`:

.Configuring the mapping with the Standalone POJO Mapper
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/pojo/standalone/mapping/config/MappingConfigurationIT.java[tags=setup]
----
<1> Start building the `SearchMapping` as usual.
<2> Access the annotation mapping context to configure annotation mapping.
<3> Access the programmatic mapping context to configure programmatic mapping.
====
