[[mapping-containerextractor]]
= [[mapper-orm-containerextractor]] Mapping container types with container extractors

[[mapping-containerextractor-basics]]
== [[mapper-orm-containerextractor-basics]] Basics

Most built-in annotations applied to properties will work transparently when applied to container types:

* `@GenericField` applied to a property of type `String` will index the property value directly.
* `@GenericField` applied to a property of type `OptionalInt` will index the optional's value (an integer).
* `@GenericField` applied to a property of type `List<String>` will index the list elements (strings).
* `@GenericField` applied to a property of type `Map<Integer, String>` will index the map values (strings).
* `@GenericField` applied to a property of type `Map<Integer, List<String>>` will index the list elements in the map values (strings).
* Etc.

Same goes for other field annotations such as `@FullTextField`,
as well as `@IndexedEmbedded` in particular.

What happens behind the scenes is that Hibernate Search will inspect the property type
and attempt to apply "container extractors", picking the first that works.

[[mapping-containerextractor-explicit]]
== [[mapper-orm-containerextractor-explicit]] [[_explicit_container_extraction]] Explicit container extraction

In some cases, you will want to pick the container extractors to use explicitly.
This is the case when a map's keys must be indexed, instead of the values.
Relevant annotations offer an `extraction` attribute to configure this,
as shown in the example below.

TIP: All built-in extractor names are available as constants
in `org.hibernate.search.mapper.pojo.extractor.builtin.BuiltinContainerExtractors`.

.Mapping `Map` keys to an index field using explicit container extractor definition
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/containerextractor/Book.java[tags=explicit-extractor]
----
<1> This annotation -- and those below -- are just Hibernate ORM configuration.
<2> Declare an index field based on the `priceByFormat` property.
<3> By default, Hibernate Search would index the map values (the book prices).
This uses the `extraction` attribute to specify that map keys (the book formats)
must be indexed instead.
====

TIP: When multiple levels of extractions are necessary,
multiple extractors can be configured:
`extraction = @ContainerExtraction(BuiltinContainerExtractors.MAP_KEY, BuiltinContainerExtractors.OPTIONAL)`.
However, such complex mappings are unlikely since they are generally not supported by Hibernate ORM.

[NOTE]
====
It is possible to implement and use custom container extractors,
but at the moment Hibernate Search will not detect that the changes to the data inside such container
must trigger the reindexing of a containing element.
Hence, the corresponding property must <<mapping-reindexing-reindexonupdate,disable reindexing on change>>.

See https://hibernate.atlassian.net/browse/HSEARCH-3688[HSEARCH-3688] for more information.
====

[[mapping-containerextractor-disabling]]
== [[mapper-orm-containerextractor-disabling]] [[_disabling_container_extraction]] Disabling container extraction

In some rare cases, container extraction is not wanted,
and the `@GenericField`/`@IndexedEmbedded` is meant to be applied to the `List`/`Optional`/etc. directly.
To ignore the default container extractors,
most annotations offer an `extraction` attribute.
Set it as below to disable extraction altogether:

.Disabling container extraction
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/containerextractor/Book.java[tags=no-extractor]
----
<1> Declare an index field based on the `authors` property.
<2> Instruct Hibernate Search to use the given bridge,
which will extract the collection size (the number of authors).
<3> Because the bridge is applied to the collection as a whole,
and not to each author,
the `extraction` attribute is used to disable container extraction.
====

[[mapping-containerextractor-programmatic]]
== [[mapper-orm-containerextractor-programmatic]] Programmatic mapping

You can pick the container extractors to use explicitly
when defining <<mapping-directfieldmapping-programmatic,fields>>
or <<mapping-indexedembedded-programmatic,indexed-embeddeds>>
through the <<mapping-programmatic,programmatic mapping>> too.
Behavior and options are identical to annotation-based mapping.

.Mapping `Map` keys to an index field using `.extractor(...)`/`.extactors(...)` for explicit container extractor definition
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/containerextractor/ContainerExtractorIT.java[tags=programmatic-extractor]
----
====

Similarly, you can disable container extraction.

.Disabling container extraction with `.noExtractors()`
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/containerextractor/ContainerExtractorIT.java[tags=programmatic-noExtractors]
----
====
