// SPDX-License-Identifier: Apache-2.0
// Copyright Red Hat Inc. and Hibernate Authors
[[mapping-entityindexmapping]]
= [[mapper-orm-entityindexmapping]] Entity/index mapping

[[mapping-entityindexmapping-basics]]
== [[mapper-orm-entityindexmapping-basics]] Basics

In order to index an entity, it must be annotated with `@Indexed`.

.Marking a class for indexing with `@Indexed`
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/entityindexmapping/Book.java[tags=indexed-default]
----
====

[NOTE]
====
Subclasses inherit the `@Indexed` annotation and will also be indexed by default.
Each indexed subclass will have its own index,
though this will be transparent when searching
(<<search-dsl-query-targeting-multiple,all targeted indexes will be queried simultaneously>>).

If the fact that `@Indexed` is inherited is a problem for your application,
you can annotate subclasses with `@Indexed(enabled = false)`.
====

By default:

* The index name will be equal to the entity name,
which in Hibernate ORM is set using the `@Entity` annotation
and defaults to the simple class name.
* With the <<mapper-orm,Hibernate ORM integration>>, the identifier of indexed documents
will be <<mapping-identifiermapping-basics,generated from the entity identifier>>.
Most types commonly used for entity identifiers are supported out of the box,
but for more exotic types you may need specific configuration.
+
With the <<mapper-pojo-standalone,Standalone POJO Mapper>>,
the identifier of indexed documents needs to be
<<mapping-identifiermapping-explicit,mapped explicitly>>.
+
See <<mapping-identifiermapping>> for details.
* The index won't have any field.
Fields must be mapped to properties explicitly.
See <<mapping-directfieldmapping>> for details.

[[mapping-entityindexmapping-explicit]]
== [[mapper-orm-entityindexmapping-explicit]] Explicit index/backend

You can change the name of the index by setting `@Indexed(index = ...)`.
Note that index names must be unique in a given application.

.Explicit index name with `@Indexed.index`
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/entityindexmapping/Author.java[tags=indexed-explicitindexname]
----
====

If you <<configuration-structure,defined named backends>>, you can map entities to another backend than the default one.
By setting `@Indexed(backend = "backend2")` you inform Hibernate Search that the index
for your entity must be created in the backend named "backend2".
This may be useful if your model has clearly defined sub-parts with very different indexing requirements.

.Explicit backend with `@Indexed.backend`
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/entityindexmapping/User.java[tags=indexed-explicitbackend]
----
====

[NOTE]
====
Entities indexed in different backends cannot be targeted by the same query.
For example, with the mappings defined above,
the following code will throw an exception
because `Author` and `User` are indexed in different backends:

[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/entityindexmapping/HibernateOrmIndexedIT.java[tags=cross-backend-search]
----
====

[[mapping-entityindexmapping-conditional-and-routing]]
== [[mapper-orm-entityindexmapping-conditional-and-routing]] [[search-mapping-indexinginterceptor]] Conditional indexing and routing

The mapping of an entity to an index is not always as straightforward as "this entity type goes to this index".
For many reasons, but mainly for performance reasons,
you may want to customize when and where a given entity is indexed:

* You may not want to index all entities of a given type: for example,
prevent indexing of entities when their `status` property is set to `DRAFT` or `ARCHIVED`,
because users are not supposed to search for those entities.
* You may want to <<concepts-sharding-routing,route entities to a specific shard of the index>>: for example,
route entities based on their `language` property,
because each user has a specific language and only searches for entities in their language.

These behaviors can be implemented in Hibernate Search by assigning a routing bridge
to the indexed entity type through `@Indexed(routingBinder = ...)`.

For more information about routing bridges, see <<binding-routingbridge>>.

[[mapping-entityindexmapping-programmatic]]
== [[mapper-orm-entityindexmapping-programmatic]] Programmatic mapping

You can mark an entity as indexed through the <<mapping-programmatic,programmatic mapping>> too.
Behavior and options are identical to annotation-based mapping.

.Marking a class for indexing with `.indexed()`
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/entityindexmapping/HibernateOrmIndexedIT.java[tags=programmatic]
----
====
