[[further-reading]]
= [[_further_reading]] Further reading

[[further-reading-hibernate-search]]
== Hibernate Search

The https://hibernate.org/search[Hibernate Search website] is a good first stop when looking
for information about Hibernate Search,
be it to know more about https://hibernate.org/search/releases/[releases],
https://hibernate.org/search/documentation/[documentation for all versions],
https://hibernate.org/search/documentation/migrate/[migration guides],
https://hibernate.org/search/roadmap/[the roadmap],
or simply getting links to the source code and issue tracker.

The Hibernate Search website also includes links to https://hibernate.org/search/more-resources/[various external resources]
such as blog posts and talks.

To contribute to, or ask questions about, Hibernate Search or any Hibernate projects,
start from the https://hibernate.org/community/[community] page on the same website.

Finally, for examples of using Hibernate Search in applications, see:

* The https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-search-orm-elasticsearch-quickstart[Quarkus quickstart],
a sample application using Hibernate Search with the <<compatibility-framework-quarkus,Quarkus>> framework.
* The https://github.com/hibernate/hibernate-search/tree/main/integrationtest/showcase/library["Library" showcase],
a sample application using Hibernate Search with the <<compatibility-framework-spring-boot,Spring Boot>> framework.
* The https://hibernate.org/search/more-resources/[blog posts and talks] mentioned above,
most of which include tutorials and/or simple applications.

[[further-reading-elasticsearch]]
== Elasticsearch

link:{elasticsearchDocUrl}[Elasticsearch's reference documentation] is an excellent starting point
to learn more about Elasticsearch.

[[further-reading-lucene]]
== Lucene

To learn more about Lucene,
you can get a copy to link:$$http://www.manning.com/hatcher3/$$[Lucene in Action (Second Edition)],
though it covers an older version of Lucene.

Otherwise, you can always try your luck with link:{luceneJavadocUrl}[Lucene's Javadoc].

[[further-reading-hibernate-orm]]
== [[_hibernate_orm]] Hibernate ORM

If you want to deepen your knowledge of Hibernate ORM,
start with the link:$$http://hibernate.org/orm/documentation/$$[online documentation] or get hold
of a copy of link:$$http://www.manning.com/bauer3/$$[Java Persistence with Hibernate, Second Edition].

[[further-reading-other]]
== Other

If you have any further questions or feedback regarding Hibernate Search,
reach out to the https://hibernate.org/community/[Hibernate community].
We are looking forward to hearing from you.

In case you would like to report a bug use the
link:$$https://hibernate.atlassian.net/browse/HSEARCH$$[Hibernate Search JIRA] instance.
