[[indexing-automatic]]
= [[mapper-orm-indexing-automatic]] [[_automatic_indexing]] Automatic indexing within Hibernate ORM

include::components/mapper-orm-only-note.asciidoc[]

By default, every time an entity is changed through a Hibernate ORM Session,
if that entity is <<mapping-entityindexmapping,mapped to an index>>,
Hibernate Search updates the relevant index.

Exactly how and when the index update happens depends on the <<coordination,coordination strategy>>;
see <<indexing-automatic-concepts>> for more information.

[[indexing-automatic-concepts]]
== [[mapper-orm-indexing-automatic-concepts]] Overview

Below is a summary of how automatic indexing works depending
on the configured <<coordination,coordination strategy>>.

Follow the links for more details.

[cols="h,2*^",options="header"]
.Comparison of automatic indexing depending on the coordination strategy
|===
|Coordination strategy
|<<coordination-none,No coordination>> (default)
|<<coordination-outbox-polling,Outbox polling>>

|Detects changes occurring in ORM sessions (`session.persist(...)`, `session.delete(...)`, setters, ...)
2+|<<indexing-automatic-concepts-changes-in-session,Yes>>

|Detects changes caused by JPQL or SQL queries (`insert`/`update`/`delete`)
2+|<<limitations-changes-in-session,No>>

|Associations must be updated on both sides
2+|<<limitations-changes-asymmetric-association-updates,Yes>>

|Changes triggering reindexing
2+|<<indexing-automatic-concepts-dirty-checking,Only relevant changes>>

|Guarantee of indexes updates
|<<coordination-none-indexing-guarantee,When the commit returns (non-transactional)>>
|<<coordination-outbox-polling-indexing-guarantee,On commit (transactional)>>

|Visibility of index updates
|<<coordination-none-indexing-visibility,Configurable: immediate (poor performance) or eventual>>
|<<coordination-outbox-polling-indexing-visibility,Eventual>>

|Overhead for application threads
|<<coordination-none-indexing-on-flush,Low to medium>>
|<<coordination-outbox-polling-indexing-background,Very low>>

|Overhead for the database
|<<coordination-none-indexing-lazy-loading,Low>>
|<<coordination-outbox-polling-indexing-full-loading,Low to medium>>
|===

[[indexing-automatic-configuration]]
== [[mapper-orm-indexing-automatic-configuration]] Configuration

Automatic indexing may be unnecessary if your index is read-only
or if you update it regularly by reindexing,
either using the  <<indexing-massindexer,`MassIndexer`>>
or <<mapper-orm-indexing-manual,manually>>.
You can disable automatic indexing by setting the configuration property
`hibernate.search.automatic_indexing.enabled` to `false`.

[[indexing-automatic-concepts-changes-in-session]]
== [[mapper-orm-indexing-automatic-concepts-changes-in-session]] In-session entity change detection and limitations

Hibernate Search uses internal events of Hibernate ORM in order to detect changes.
These events will be triggered if you actually manipulate managed entity objects in your code:
calls o `session.persist(...)`, `session.delete(...)`, to entity setters, etc.

This works great for most applications, but you need to consider some limitations:

* <<limitations-changes-in-session>>
* <<limitations-changes-asymmetric-association-updates>>

[[indexing-automatic-concepts-dirty-checking]]
== [[mapper-orm-indexing-automatic-concepts-dirty-checking]] Dirty checking
Hibernate Search is aware of the entity properties that are accessed when building indexed documents.
When processing Hibernate ORM entity change events, it is also aware of which properties actually changed.
Thanks to that knowledge, it is able to detect which entity changes are actually relevant to indexing,
and to skip reindexing when a property is modified, but does not affect the indexed document.

You can control this "dirty checking" by setting
the <<configuration-property-types,boolean property>> `hibernate.search.automatic_indexing.enable_dirty_check`:

* by default, or when set to `true`,
Hibernate Search will consider whether modified properties are relevant
before triggering reindexing.
* when set to `false`, Hibernate Search will trigger reindexing upon any change,
regardless of the entity properties that changed.

[[indexing-automatic-synchronization]]
== Synchronization with the indexes

Automatic indexing is affected by the synchronization strategy in use in the `SearchSession`.

See <<indexing-plan-synchronization,this section>> for more information.

[[indexing-plan-filter]]
== Indexing plan filter

include::components/incubating-warning.asciidoc[]

In some scenarios, it might be helpful to pause the indexing programmatically, for example,
when importing larger amounts of data. Hibernate Search allows configuring application-wide
and session-level filters to manage which types are tracked for changes and indexed.

.Configuring an application-wide filter
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/automaticindexing/HibernateOrmIndexingPlanFilterIT.java[tags=application-filter]
----
Configuring an application-wide filter requires an instance of the `SearchMapping`.

<1> <<entrypoints-search-mapping,Retrieve the `SearchMapping`>>.
<2> Start the declaration of the indexing plan filter.
<3> Configure included/excluded types through the `SearchIndexingPlanFilter`
====

.Configuring a session-level filter
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/automaticindexing/HibernateOrmIndexingPlanFilterIT.java[tags=session-filter]
----
Configuring a session level filter is available through an instance of the `SearchSession`.

<1> <<entrypoints-search-session,Retrieve the `SearchSession`>>
<2> Configure included/excluded types through the `SearchIndexingPlanFilter`
====

Filter can be defined by providing indexed and contained types as well as their supertypes.
Interfaces are not allowed and passing an interface class to any of the filter definition methods will result in an exception.
If dynamic types represented by a `Map` are used then their names must be used to configure the filter.
Filter rules are:

* If the type `A` is explicitly included by the filter, then a change to an object that is exactly of a type `A` is processed.
* If the type `A` is explicitly excluded by the filter, then a change to an object that is exactly of a type `A` is ignored.
* If the type `A` is explicitly included by the filter, then a change to an object that is exactly of a type `B`,
which is a subtype of the type `A`, is processed unless the filter explicitly excludes a more specific supertype of a type `B`.
* If the type `A` is excluded by the filter explicitly, then a change to an object that is exactly of a type `B`,
which is a subtype of type the `A`, is ignored unless the filter explicitly includes a more specific supertype of a type `B`.

A session-level filter takes precedence over an application-wide one. If the session-level filter configuration does not
either explicitly or through inheritance include/exclude the exact type of an entity, then the decision will be made by
the application-wide filter. If an application-wide filter also has no explicit configuration for a type, then this type
is considered to be included.

In some cases we might need to disable the indexing entirely. Listing all entities one by one might be cumbersome,
but since filter configuration is implicitly applied to subtypes, `.exclude(Object.class)` can be used to exclude all types.
Conversely, `.include(Object.class)` can be used to enable indexing within a session filter when
the application-wide filter disables indexing completely.

.Disable all indexing within a session
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/automaticindexing/HibernateOrmIndexingPlanFilterIT.java[tags=session-filter-exclude-all]
----
Configuring a session level filter is available through an instance of the `SearchSession`.

<1> <<entrypoints-search-session,Retrieve the `SearchSession`>>
<2> Excluding `Object.class` will lead to excluding all its subtypes which means nothing will be included.
====

.Enable indexing in the session while application-wide indexing is paused
====
[source, JAVA, indent=0, subs="+callouts"]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/automaticindexing/HibernateOrmIndexingPlanFilterIT.java[tags=session-filter-exclude-include-all-application]
----
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/automaticindexing/HibernateOrmIndexingPlanFilterIT.java[tags=session-filter-exclude-include-all-session]
----

<1> <<entrypoints-search-mapping,Retrieve the `SearchMapping`>>.
<2> An application-wide filter disables any indexing
<3> <<entrypoints-search-session,Retrieve the `SearchSession`>>
<4> A session level filter re-enables indexing *for changes happening in current session only*
====

[NOTE]
====
Trying to configure the same type as both included and excluded at the same time by the same filter
will lead to an exception being thrown.
====

[NOTE]
====
Only an application-wide filter is safe to use when using the <<coordination-database-polling,`outbox-polling` coordination strategy>>.
When this coordination strategy is in use, entities are loaded and indexed in a different session from
the one where they were changed. It might lead to unexpected results as the session where events are processed will not
apply the filter configured by the session in which entities were modified.
An exception will be thrown if such a filter is configured unless this filter excludes all the types to prevent any
unexpected consequences of configuring session-level filters with this coordination strategy.
====
