[[mapper-orm]]
= [[mapper-orm-mapping-configuration]] Hibernate ORM integration

[[mapper-orm-basics]]
== Basics

The Hibernate ORM <<architecture-hsearch-components-mapper,"mapper">> is an integration of Hibernate Search into Hibernate ORM.

Its key features include:

* <<indexing-automatic,Automatic indexing>> of Hibernate ORM entities
as they are modified in the Hibernate ORM `EntityManager`/`Session`.
* <<search-dsl-query-entity-loading-options,Loading of managed entities>>
as hits in the result of a <<search-dsl-query,search query>>.

[[mapper-orm-startup]]
== [[mapper-orm-mapping-configuration-enabling-disabling]] [[search-configuration-event]] Startup

The Hibernate Search integration into Hibernate ORM will start automatically,
at the same time as Hibernate ORM, as soon as it is present in the classpath.

If for some reason you need to prevent Hibernate Search from starting,
set the <<configuration-property-types,boolean property>> `hibernate.search.enabled` to `false`.

[[mapper-orm-shutdown]]
== Shutdown

The Hibernate Search integration into Hibernate ORM will stop automatically,
at the same time as Hibernate ORM.

On shutdown, Hibernate Search will stop accepting new indexing requests:
new indexing attempts will throw exceptions.
The Hibernate ORM shutdown will block until all ongoing indexing operations complete.

[[mapper-orm-mapping-dynamicmap]]
== [[mapper-orm-programmatic-mapping-dynamicmap]] Mapping `Map`-based models

link:{hibernateDocUrl}#dynamic-model["Dynamic-map" entity models],
i.e. models based on `java.util.Map` instead of custom classes,
cannot be mapped using annotations.
However, they can be mapped using the <<mapping-programmatic,programmatic mapping API>>.
You just need to refer to the types by their name using `context.programmaticMapping().type("thename")`:

* Pass the entity name for dynamic entity types.
* Pass the "role" for dynamic embedded/component types,
i.e. the name of the owning entity, followed by a dot ("."),
followed by the dot-separated path to the component in that entity.
For example `MyEntity.myEmbedded` or `MyEntity.myEmbedded.myNestedEmbedded`.

[[mapper-orm-configuration-other]]
== [[mapper-orm-mapping-configuration-other]] Other configuration

Other configuration properties are mentioned in the relevant parts of this documentation.
You can find a full reference of available properties in the Hibernate Search javadoc:
link:{hibernateSearchJavadocUrl}/org/hibernate/search/mapper/orm/cfg/HibernateOrmMapperSettings.html[org.hibernate.search.mapper.orm.cfg.HibernateOrmMapperSettings].
