[[migrating]]
== [[getting-started-migrating]] Migrating

If you are upgrading an existing application from an earlier version of Hibernate Search to the latest release,
make sure to check out the http://hibernate.org/search/documentation/migrate/[migration guide].

[WARNING]
====
**To Hibernate Search 5 users**

If you pull our artifacts from a Maven repository, and you come from Hibernate Search 5,
be aware that just bumping the version number will not be enough.

In particular, the group IDs changed from `org.hibernate` to `org.hibernate.search`,
most of the artifact IDs changed to reflect the new mapper/backend design,
and the Lucene integration now requires an explicit dependency instead of being available by default.
Read <<mapper-orm-getting-started-dependencies>> for more information.

Additionally, be aware that a lot of APIs changed, some only because of a package change,
others because of more fundamental changes
(like moving away from using Lucene types in Hibernate Search APIs).
====
