[[schema-management]]
= [[mapper-orm-schema-management]] Managing the index schema

[[schema-management-basics]]
== [[mapper-orm-schema-management-basics]] Basics

Before indexes can be used for indexing or searching, they must be created on disk (Lucene) or in the remote cluster (Elasticsearch).
With Elasticsearch in particular, this creation may not be obvious since it requires to describe the schema for each index,
which includes in particular:

* the definition of every analyzer or normalizer used in this index;
* the definition of every single field used in this index,
including in particular its type, the analyzer assigned to it, whether it requires doc values, etc.

Hibernate Search has all the necessary information to generate this schema automatically,
so it is possible to delegate the task of managing the schema to Hibernate Search.

[[schema-management-strategy]]
== [[mapper-orm-schema-management-strategy]] Automatic schema management on startup/shutdown

The property `hibernate.search.schema_management.strategy` can be set to one of the following values
in order to define what to do with the indexes and their schema on startup and shutdown.

[cols="1a,2a,1a",options="header"]
|====
|Strategy|Definition|Warnings
|[[mapper-orm-schema-management-strategy-none]]`none`
|A strategy that does not do anything on startup or shutdown.

Indexes and their schema will not be created nor deleted on startup or shutdown.
Hibernate Search will **not even check** that the index actually exists.
|With Elasticsearch, indexes and their schema will have to be created explicitly before startup.
|[[mapper-orm-schema-management-strategy-validate]]`validate`
|A strategy that does not change indexes nor their schema,
but checks that indexes exist and validates their schema on startup.

An exception will be thrown on startup if:

* Indexes are missing
* OR, with the Elasticsearch backend only, indexes exist but their schema does not match the requirements
of the Hibernate Search mapping:
missing fields, fields with incorrect type, missing analyzer definitions or normalizer definitions, ...

"Compatible" differences such as extra fields <<schema-management-concepts-validation-permissive, are ignored>>.
|Indexes and their schema will have to be created explicitly before startup.

With the Lucene backend, validation is limited to checking that the indexes exist,
because <<schema-management-concepts-lucene-schema,local Lucene indexes don't have a schema>>.
|[[schema-management-strategy-create]]`create`
|[[mapper-orm-schema-management-strategy-create]]A strategy that creates missing indexes and their schema on startup,
but does not touch existing indexes and assumes their schema is correct without validating it.
|<<schema-management-concepts-massindexing,Creating a schema does not populate indexed data>>.
|[[schema-management-strategy-create-or-validate]]`create-or-validate` (**default**)
|[[mapper-orm-schema-management-strategy-create-or-validate]]A strategy that creates missing indexes and their schema on startup,
and validates the schema of existing indexes.

With the Elasticsearch backend only, an exception will be thrown on startup if some indexes already exist
but their schema does not match the requirements of the Hibernate Search mapping:
missing fields, fields with incorrect type, missing analyzer definitions or normalizer definitions, ...

"Compatible" differences such as extra fields <<schema-management-concepts-validation-permissive, are ignored>>.
|<<schema-management-concepts-massindexing,Creating a schema does not populate indexed data>>.

With the Lucene backend, validation is limited to checking that the indexes exist,
because <<schema-management-concepts-lucene-schema,local Lucene indexes don't have a schema>>.
|[[schema-management-strategy-create-or-update]]`create-or-update`
|[[mapper-orm-schema-management-strategy-create-or-update]]A strategy that creates missing indexes and their schema on startup,
and updates the schema of existing indexes if possible.
|<<schema-management-concepts-massindexing,Updating a schema does not update indexed data>>.

**This strategy is unfit for production environments**,
due to several limitations including
<<schema-management-concepts-update-failure,the impossibility to change the type of an existing field>>
or <<schema-management-concepts-index-closing,the requirement to close indexes while updating analyzer definitions>>
(which is not possible at all on AWS).

With the Lucene backend, schema update is a no-op,
because <<schema-management-concepts-lucene-schema,local Lucene indexes don't have a schema>>.
|[[mapper-orm-schema-management-strategy-drop-and-create]]`drop-and-create`
|A strategy that drops existing indexes and re-creates them and their schema on startup.
|<<schema-management-concepts-drop-loses-data,All indexed data will be lost>> on startup.
|[[mapper-orm-schema-management-strategy-drop-and-create-and-drop]]`drop-and-create-and-drop`
|A strategy that drops existing indexes and re-creates them and their schema on startup,
then drops the indexes on shutdown.
|<<schema-management-concepts-drop-loses-data,All indexed data will be lost>> on startup and shutdown.
|====

[[schema-management-manager]]
== [[mapper-orm-schema-management-manager]] Manual schema management

Schema management does not have to happen automatically on startup and shutdown.

Using the `SearchSchemaManager` interface,
it is possible to trigger schema management operations explicitly
after Hibernate Search has started.

[TIP]
====
The most common use case is to set the <<schema-management-strategy,automatic schema management strategy>> to `none`
and handle the creation/deletion of indexes manually when some other conditions are met,
for example the Elasticsearch cluster has finished booting.

After schema management operations are complete,
you will often want to populate indexes.
To that end, use the <<indexing-massindexer,mass indexer>>.
====

The `SearchSchemaManager` interface exposes the following methods.

[cols="1a,2a,1a",options="header"]
|====
|Method|Definition|Warnings
|[[mapper-orm-schema-management-manager-validate]]`validate()`
|Does not change indexes nor their schema,
but checks that indexes exist and validates their schema.
|With the Lucene backend, validation is limited to checking that the indexes exist,
because <<schema-management-concepts-lucene-schema,local Lucene indexes don't have a schema>>.
|[[mapper-orm-schema-management-manager-create-if-missing]]`createIfMissing()`
|Creates missing indexes and their schema,
but does not touch existing indexes and assumes their schema is correct without validating it.
|<<schema-management-concepts-massindexing,Creating a schema does not populate indexed data>>.
|[[mapper-orm-schema-management-manager-create-or-validate]]`createOrValidate()`
|Creates missing indexes and their schema,
and validates the schema of existing indexes.
|<<schema-management-concepts-massindexing,Creating a schema does not populate indexed data>>.

With the Lucene backend, validation is limited to checking that the indexes exist,
because <<schema-management-concepts-lucene-schema,local Lucene indexes don't have a schema>>.
|[[mapper-orm-schema-management-manager-create-or-update]]`createOrUpdate()`
|Creates missing indexes and their schema,
and updates the schema of existing indexes if possible.
|<<schema-management-concepts-massindexing,Updating a schema does not update indexed data>>.

With the Elasticsearch backend, <<schema-management-concepts-update-failure,updating a schema may fail>>.

With the Elasticsearch backend, <<schema-management-concepts-index-closing,updating a schema may close indexes while updating analyzer definitions>>
(which is not possible at all on AWS).

With the Lucene backend, schema update is a no-op,
because <<schema-management-concepts-lucene-schema,local Lucene indexes don't have a schema>>.
(it just creates missing indexes).
|[[mapper-orm-schema-management-manager-drop-if-existing]]`dropIfExisting()`
|Drops existing indexes.
|<<schema-management-concepts-drop-loses-data,All indexed data will be lost>>.
|[[mapper-orm-schema-management-manager-drop-and-create]]`dropAndCreate()`
|Drops existing indexes and re-creates them and their schema.
|<<schema-management-concepts-drop-loses-data,All indexed data will be lost>>.
|====

Below is an example using a `SearchSchemaManager` to drop and create indexes,
then using a <<indexing-massindexer,mass indexer>> to re-populate the indexes.
The
<<indexing-massindexer-parameters-drop-and-create-schema,`dropAndCreateSchemaOnStart` setting of the mass indexer>>
would be an alternative solution to achieve the same results.

.Reinitializing indexes using a `SearchSchemaManager`
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/schema/management/HibernateOrmSchemaManagerIT.java[tags=simple]
----
<1> <<entrypoints-search-session,Retrieve the `SearchSession`>>.
<2> Get a schema manager.
<3> Drop and create the indexes.
This method is synchronous and will only return after the operation is complete.
<4> Optionally, trigger <<indexing-massindexer,mass indexing>>.
====

You can also select entity types when creating a schema manager,
to manage the indexes of these types only (and their indexed subtypes, if any):

.Reinitializing only some indexes using a `SearchSchemaManager`
====
[source, JAVA, indent=0]
----
include::{sourcedir}/org/hibernate/search/documentation/mapper/orm/schema/management/HibernateOrmSchemaManagerIT.java[tags=select-type]
----
<1> Get a schema manager targeting the index mapped to the `Book` entity type.
<2> Drop and create the index for the `Book` entity only.
Other indexes are unaffected.
====

[[schema-management-concepts]]
== [[mapper-orm-schema-management-concepts]] How schema management works

[[schema-management-concepts-massindexing]]
 [[mapper-orm-schema-management-concepts-massindexing]]Creating/updating a schema does not create/update indexed data::
Creating or updating indexes and their schema through schema management
will not populate the indexes:

* newly created indexes will always be empty.
* indexes with a recently updated schema will still contain the same indexed data,
i.e. new fields won't be added to documents just because they were added to the schema.

This is by design: reindexing is a potentially long-running task that should be triggered explicitly.
To populate indexes with pre-existing data from the database,
use <<indexing-massindexer,mass indexing>>.

[[schema-management-concepts-drop-loses-data]]
 [[mapper-orm-schema-management-concepts-drop-loses-data]]Dropping the schema means losing indexed data::

Dropping a schema will drop the whole index, including all indexed data.
+
A dropped index will need to be re-created through schema management,
then populated with pre-existing data from the database through <<indexing-massindexer,mass indexing>>.
[[schema-management-concepts-lucene-schema]]
 [[mapper-orm-schema-management-concepts-lucene-schema]]Schema validation and update are not effective with Lucene::
The Lucene backend will only validate that the index actually exists and create missing indexes,
because there is no concept of schema in Lucene
beyond the existence of index segments.
[[schema-management-concepts-validation-permissive]]
 [[mapper-orm-schema-management-concepts-validation-permissive]]Schema validation is permissive::
With Elasticsearch, schema validation is as permissive as possible:

* Fields that are unknown to Hibernate Search will be ignored.
* Settings that are more powerful than required will be deemed valid.
For example, a field that is not marked as sortable in Hibernate Search
but marked as `"docvalues": true` in Elasticsearch will be deemed valid.
* Analyzer/normalizer definitions that are unknown to Hibernate Search will be ignored.

+
One exception: date formats must match exactly the formats specified by Hibernate Search,
due to implementation constraints.
[[schema-management-concepts-update-failure]]
 [[mapper-orm-schema-management-concepts-update-failure]]Schema updates may fail::
A schema update, triggered by the `create-or-update` strategy, may simply fail.
This is because schemas may change in an incompatible way, such as a field having its type changed,
or its analyzer changed, etc.
+
Worse, since updates are handled on a per-index basis,
a schema update may succeed for one index but fail on another,
leaving your schema as a whole half-updated.
+
For these reasons, **using schema updates in a production environment is not recommended**.
Whenever the schema changes, you should either:

* drop and create indexes, then <<indexing-massindexer,reindex>>.
* OR update the schema manually through custom scripts.

+
In this case, the `create-or-update` strategy will prevent Hibernate Search from starting,
but it may already have successfully updated the schema for another index, making a rollback difficult.
[[schema-management-concepts-index-closing]]
 [[mapper-orm-schema-management-concepts-index-closing]]Schema updates on Elasticsearch may close indexes::
Elasticsearch does not allow updating analyzer/normalizer definitions on an open index.
Thus, when analyzer or normalizer definitions have to be updated during a schema update,
Hibernate Search will temporarily stop the affected indexes.
+
For this reason, the `create-or-update` strategy should be used with caution
when multiple clients use Elasticsearch indexes managed by Hibernate Search:
those clients should be synchronized in such a way that while Hibernate Search is starting,
no other client needs to access the index.
+
Also, since Elasticsearch on Amazon Web Services (AWS)
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-es-operations.html[does not support the `_close`/`_open` operations],
**the schema update will fail** when trying to update analyzer definitions
on an AWS Elasticsearch cluster.
The only workaround is to avoid the schema update on AWS.
It should be avoided in production environments regardless:
see <<schema-management-concepts-update-failure>>.
