CREATE SCHEMA IF NOT EXISTS JBATCH;
SET SCHEMA JBATCH;
CREATE TABLE IF NOT EXISTS JOBINSTANCEDATA
(
    jobinstanceid BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name          VARCHAR(512),
    apptag        VARCHAR(512)
);
CREATE TABLE IF NOT EXISTS EXECUTIONINSTANCEDATA
(
    jobexecid     BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    jobinstanceid BIGINT,
    createtime    TIMESTAMP,
    starttime     TIMESTAMP,
    endtime       TIMESTAMP,
    updatetime    TIMESTAMP,
    parameters    BLOB,
    batchstatus   VARCHAR(512),
    exitstatus    VARCHAR(512),
    CONSTRAINT JOBINST_JOBEXEC_FK FOREIGN KEY (jobinstanceid) REFERENCES JOBINSTANCEDATA (jobinstanceid) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS STEPEXECUTIONINSTANCEDATA
(
    stepexecid       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    jobexecid        BIGINT,
    batchstatus      VARCHAR(512),
    exitstatus       VARCHAR(512),
    stepname         VARCHAR(512),
    readcount        INTEGER,
    writecount       INTEGER,
    commitcount      INTEGER,
    rollbackcount    INTEGER,
    readskipcount    INTEGER,
    processskipcount INTEGER,
    filtercount      INTEGER,
    writeskipcount   INTEGER,
    startTime        TIMESTAMP,
    endTime          TIMESTAMP,
    persistentData   BLOB,
    CONSTRAINT JOBEXEC_STEPEXEC_FK FOREIGN KEY (jobexecid) REFERENCES EXECUTIONINSTANCEDATA (jobexecid) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS JOBSTATUS
(
    id  BIGINT PRIMARY KEY,
    obj BLOB,
    CONSTRAINT JOBSTATUS_JOBINST_FK FOREIGN KEY (id) REFERENCES JOBINSTANCEDATA (jobinstanceid) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS STEPSTATUS
(
    id  BIGINT PRIMARY KEY,
    obj BLOB,
    CONSTRAINT STEPSTATUS_STEPEXEC_FK FOREIGN KEY (id) REFERENCES STEPEXECUTIONINSTANCEDATA (stepexecid) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS CHECKPOINTDATA
(
    id  VARCHAR(512),
    obj BLOB
);
