[IMPORTANT]
====
There are a few constraints to keep in mind when annotating a custom projection type:

* The custom projection type must be in the same JAR as entity types,
or Hibernate Search will <<mapping-projection-type-detection,require additional configuration>>.
* When projecting on value fields or object fields, the path to the projected field
is inferred from the constructor parameter name by default,
but <<mapping-projection-inner-inference-fieldpath,inference will fail if constructor parameter names are not included in the Java bytecode>>.
Alternatively the path can be provided explicitly
through <<search-dsl-projection-field-mapping,`@FieldProjection(path = ...)`>>/<<search-dsl-projection-object-mapping,`@ObjectProjection(path = ...)`>>,
in which case Hibernate Search won't rely on constructor parameter names.
* When projecting on value fields, the constraints of the <<search-dsl-projection-field,`field`>> projection still apply.
In particular, with the <<backend-lucene,Lucene backend>>, value fields involved in the projection
must be configured as <<mapping-directfieldmapping-projectable,projectable>>.
* When projecting on object fields, the constraints of the <<search-dsl-projection-object,`object`>> projection still apply.
In particular, with the <<backend-lucene,Lucene backend>>, multi-valued object fields involved in the projection
must be configured as <<mapping-indexedembedded-structure-nested,nested>>.
====
